package com.example.SpringHibernate;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringHibernateApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringHibernateApplication.class, args);
	}

}
/*
 Step 8: Run and Test the Application

Run Your Application:
In your IDE, run the DemoApplication.java class (the main class generated by Spring Initializr).

Use Postman to Test the API:
POST /api/people: To create a new person.
GET /api/people: To get all people.
GET /api/people/{id}: To get a person by ID.
DELETE /api/people/{id}: To delete a person by ID.
 */